name: mathsgames
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  tuple: ^2.0.2


  path_provider: ^2.1.4

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.15.3

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2

  # JSON / Codegen
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  # UI & Widgets
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.0
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.3

  # Utils
  url_launcher: ^6.3.1
  device_info_plus: ^12.1.0
  audioplayers: ^6.0.0

  # PDF / Export
  pdf: ^3.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.1
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/imgYellow/
    - assets/imgGreen/
    - assets/imgBlue/
    - assets/imgBlueDark/
    - assets/imgGreenDark/
    - assets/imgYellowDark/
    - assets/tick.mp3
    - assets/wrong.mp3
    - assets/right.mp3
    - assets/gameover.mp3
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: OriginalSurfer
      fonts:
        - asset: assets/fonts/OriginalSurfer-Regular.ttf
          weight: 700
    - family: Latinotype
      fonts:
        - asset: assets/fonts/Latinotype - Moranga Bold.otf
          weight: 800
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic

flutter_intl:
  enabled: true