name: mathsgames
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.4.1
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.10+1
  get_it: ^8.2.0
  vsync_provider: ^0.5.0
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  tuple: ^2.0.0
  fluttertoast: ^9.0.0
  audioplayers: ^6.0.0
  step_progress_indicator: ^1.0.2
  percent_indicator: ^4.2.2
  auto_size_text: ^3.0.0
  flutter_switch: ^0.3.2
  url_launcher: ^6.1.2
  device_info_plus: ^12.1.0
  flutter_rating_bar: ^4.0.0
  launch_review: ^3.0.1
  flutter_email_sender: ^8.0.0
  flutter_share: ^2.0.0
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/imgYellow/
    - assets/imgGreen/
    - assets/imgBlue/
    - assets/imgBlueDark/
    - assets/imgGreenDark/
    - assets/imgYellowDark/
    - assets/tick.mp3
    - assets/wrong.mp3
    - assets/right.mp3
    - assets/gameover.mp3
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: OriginalSurfer
      fonts:
        - asset: assets/fonts/OriginalSurfer-Regular.ttf
          weight: 700
    - family: Latinotype
      fonts:
        - asset: assets/fonts/Latinotype - Moranga Bold.otf
          weight: 800
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic

flutter_intl:
  enabled: true

# ✅ Local overrides for AGP/Dart fixes
dependency_overrides:
  figma_squircle:
    path: lib/overrides/figma_squircle

# flutter_email_sender:
#   path: lib/overrides/flutter_email_sender

# flutter_share:
#   path: lib/overrides/flutter_share

# flutter_vibrate:
#   path: lib/overrides/flutter_vibrate

# launch_review:
#   path: lib/overrides/launch_review